[GLOBAL]
LOGICS=SimplexLogic,ReflectorLogic
CFG_DIR=svxlink.d
TIMESTAMP_FORMAT="%c"
CARD_SAMPLE_RATE=16000
CARD_CHANNELS=1
LINKS=AllLink
#LOCATION_INFO=LocationInfo

[SimplexLogic]
TYPE=Simplex
RX=Rx1
TX=Tx1
CALLSIGN=F7ABC
MODULES=ModuleParrot
TIME_FORMAT=24
SHORT_IDENT_INTERVAL=15
LONG_IDENT_INTERVAL=60
#LONG_ANNOUNCE_ENABLE=1
#LONG_ANNOUNCE_FILE=/usr/share/svxlink/sounds/fr_FR/Custom/balise_longue.wav
IDENT_ONLY_AFTER_TX=0
EVENT_HANDLER=/usr/share/svxlink/events.tcl
DEFAULT_LANG=fr_FR
RGR_SOUND_DELAY=1
RGR_SOUND_ALWAYS=1
FX_GAIN_NORMAL=0
FX_GAIN_LOW=-6
EXEC_CMD_ON_SQL_CLOSE=500



[ReflectorLogic]
TYPE=Reflector
HOSTS=reflector1.f4ipa.fr
CALLSIGN=F7ABC
AUTH_KEY=517388
EVENT_HANDLER=/usr/share/svxlink/events.tcl
MONITOR_TGS=20899
DEFAULT_TG=20899
TG_SELECT_TIMEOUT=-1
DEFAULT_LANG=fr_FR
ANNOUNCE_REMOTE_MIN_INTERVAL=999999
MUTE_FIRST_TX_LOC=0


[AllLink]
CONNECT_LOGICS=SimplexLogic,ReflectorLogic
DEFAULT_ACTIVE=1
TIMEOUT=0

[Rx1]
TYPE=Local
AUDIO_DEV=alsa:plughw:0
AUDIO_CHANNEL=0
SQL_DET=HIDRAW
HID_DEVICE=/dev/hidraw0
HID_SQL_PIN=VOL_DN
SQL_HANGTIME=500
SQL_TIMEOUT=180
DEEMPHASIS=0
PREAMP=0
LIMITER_THRESH=-3
DTMF_DEC_TYPE=INTERNAL
DTMF_MUTING=1
DTMF_HANGTIME=50


[Tx1]
TYPE=Local
AUDIO_DEV=alsa:plughw:0
AUDIO_CHANNEL=0
PTT_TYPE=Hidraw
HID_DEVICE=/dev/hidraw0
HID_PTT_PIN=GPIO3
PTT_HANGTIME=500
PREEMPHASIS=0
MASTER_GAIN=0
LIMITER_THRESH=-3
TIMEOUT=900


[LocationInfo]
STATUS_SERVER_LIST=aprs.echolink.org:5199
APRS_SERVER_LIST=euro.aprs2.net:14580
LAT_POSITION=0.0.0N
LON_POSITION=00.00.00E
CALLSIGN=EL-F7ABC
SOURCE_CALLSIGN=F7ABC
#FREQUENCY=000.000
#TX_POWER=00
ANTENNA_GAIN=0
BEACON_INTERVAL=10
SYMBOL=/r
COMMENT="RI49 France Multiprotocole"